Added Test Cases
Vebhavdaa/task pull request #1
Opened 2024-03-20 07:59 UTC by Vebhavdaa

Added test cases for 
app.tsx
footer-comp.tsx
menu-header.tsx
site-name-header.tsx
load-more-button.tsx, 
news-card.tsx

2024-03-20 08:06 UTC, Vebhavdaa commented
Addressed previous issues like :

Use data-testid and getByTestId for elements as much as possible
Use assertions to cover each and every statement(tried for max)
Try to reach maximum test coverage

2024-03-21 10:14 UTC, aashitk requested changes
@Vebhavdaa Added few change requests.
Make sure to make similar changes in other places as well.

2024-03-21 10:14 UTC, aashitk commented on package.json
>      "@testing-library/user-event": "^13.5.0",
This can be in devDependencies

2024-03-21 10:14 UTC, aashitk commented on src/App.test.tsx
News card component is mocked but not tested.

2024-03-21 10:14 UTC, aashitk commented on src/components/menu-header.test.tsx
> +    const pastButton = getByTestId("past-button");
Should add assertions for this components below

2024-03-21 10:14 UTC, aashitk commented on src/components/footer-comp.test.tsx
You need to mock AppBar and Toolbar, and test it using assertions

2024-03-21 10:14 UTC, aashitk commented on src/components/footer-comp.test.tsx
> +    const logoImage = getByAltText('Vector');
Since data-testid is present, why not use it to get element

2024-03-21 10:14 UTC, aashitk commented on src/components/news-card.test.tsx
> +    expect(metadataElement.textContent).toMatch(expectedScoreRegex);
Do not use RegExp, check exact value that is expected to show up

2024-03-21 10:14 UTC, aashitk commented on src/components/site-name-header.test.tsx
> +    const logoImage = getByAltText('headerlogo');
Why not have data-testid like footer component?

2024-03-27 05:02 UTC, aashitk requested changes
Minor change requested

2024-03-27 05:02 UTC, aashitk commented on src/App.tsx
> +    <AppContextProvider>
Put context provider out of App.tsx. It's a good practice.

2024-03-27 05:02 UTC, aashitk commented on src/AppContext.test.tsx
> +    expect(contextCheck).toBeInTheDocument();
Should also check the text being rendered.

2024-03-28 06:36 UTC, aashitk approved these changes

2024-03-28 06:47 UTC, merged