Added e2e cypress tests
Vebhavdaa/task pull request #3
Opened 2024-03-28 17:02 UTC by Vebhavdaa

Added End 2 End tests using Cypress

2024-04-01 08:20 UTC, aashitk requested changes
Added few comments to address changes or provide appropriate reply.
Also can you get rid of `tsconfig 2.json` as well?

2024-04-01 08:20 UTC, aashitk commented on cypress/e2e/homepage.cy.ts
> +      }
Why we need if condition here?

2024-04-01 08:20 UTC, aashitk commented on cypress/e2e/homepage.cy.ts
> +  });
Check assertion of news-cards as well.

2024-04-01 08:20 UTC, aashitk commented on cypress/e2e/homepage.cy.ts
> +  });
Check assertion of news-cards as well.

2024-04-01 08:20 UTC, aashitk commented on cypress/e2e/homepage.cy.ts
> +    cy.get('[data-testid="news-card"]').first().click();
This it block is missing assertion to check navigation.

2024-04-01 08:20 UTC, aashitk commented on cypress/e2e/homepage.cy.ts
> +    cy.get('[data-testid="news-card"]').should("have.length", 10);
Better if you check length of cards before as well as after load-more button is clicked

2024-04-01 12:14 UTC, MyNewGitHere commented on cypress/e2e/homepage.cy.ts
> +      }
if condition provides a safety check to handle potential scenarios where the intercepted response may not be available

2024-04-02 06:00 UTC, aashitk commented on cypress/e2e/homepage.cy.ts
> +      }
Tests should always be absolute, avoid conditional testing as much as possible.
If it fails due to potential scenarios, let it fail. That will give us surety our Cypress tests work fine and show failures of API as well.
This makes sure if Cypress works successfully, API is working fine and won't break in real-time execution.

2024-04-02 06:04 UTC, aashitk commented on cypress/e2e/homepage.cy.ts
> +        if (href) {
Remove `if` condition, verify directly.

2024-04-02 06:05 UTC, aashitk requested changes
Minor comment

2024-04-02 07:35 UTC, aashitk approved these changes
LGTM

2024-04-02 07:37 UTC, merged